
==============
Directory tree
==============

GitHub project directory tree:

**oldtree**
  Kernel source code

**phantom**
  Kernel libaries and subsystems source code

**plib**
  Phantom user mode libraries

**run**
  Setup for running Phantom OS in QEMU

**test**
  CI tests for various subsystems

**tools**
  Non-kernel code, tools to support OS
  programming. Notably here is *plc*, 
  Phantom Language Compiler.

  **plc**
    Phantom Language Compiler. Also 
    Java to Phantom translator, and 
    preliminary code for Python to 
    Phantom translator.

  **pfsextract**
    Tool to extract persistent memory image
    from Phatom disk image file.

    

**build**
  Built executables for tools, scripts.  

